name: Toffium-forge

on:
  push:
    branches: [ MC-1.16.4 ]
  pull_request:
    branches: [ MC-1.16.4 ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ustaw JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Ustaw potrzebne informacje
      run: |
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         git config --global gc.auto 0
         sudo chmod -R -f 777 ./gradlew
         
    - name: Skompiluj modyfikacje
      run: | 
           ./gradlew build
           ./gradlew clean build
        
    - name: UdostÄ™pnij artefakt
      uses: actions/upload-artifact@v2
      with:
        name: Toffium-forge
        path: '*.jar'
      
